import { Product } from './types';

export const mockProducts: Product[] = [
  // Drinks
  {
    id: '1',
    name: 'Espresso',
    nameAr: 'إسبريسو',
    priceUSD: 3.5,
    category: 'Drinks',
    barcode: '001',
    stock: 100,
    minStockLevel: 10,
    cost: 1.2,
    stockStatus: 'in-stock',
  },
  {
    id: '2',
    name: 'Cappuccino',
    nameAr: 'كابتشينو',
    priceUSD: 4.5,
    category: 'Drinks',
    barcode: '002',
    stock: 85,
    minStockLevel: 10,
    cost: 1.5,
    stockStatus: 'in-stock',
  },
  {
    id: '3',
    name: 'Latte',
    nameAr: 'لاتيه',
    priceUSD: 4.0,
    category: 'Drinks',
    barcode: '003',
    stock: 10,
    minStockLevel: 10,
    cost: 1.4,
    stockStatus: 'low-stock',
  },
  {
    id: '4',
    name: 'Americano',
    nameAr: 'أمريكانو',
    priceUSD: 3.0,
    category: 'Drinks',
    barcode: '004',
    stock: 0,
    minStockLevel: 10,
    cost: 1.0,
    stockStatus: 'out-of-stock',
  },
  {
    id: '5',
    name: 'Orange Juice',
    nameAr: 'عصير برتقال',
    priceUSD: 5.0,
    category: 'Drinks',
    barcode: '005',
    stock: 45,
    minStockLevel: 10,
    cost: 2.0,
    stockStatus: 'in-stock',
  },

  // Food
  {
    id: '6',
    name: 'Caesar Salad',
    nameAr: 'سلطة سيزر',
    priceUSD: 8.5,
    category: 'Food',
    barcode: '101',
    stock: 30,
    minStockLevel: 8,
    cost: 3.5,
    stockStatus: 'in-stock',
  },
  {
    id: '7',
    name: 'Club Sandwich',
    nameAr: 'ساندويتش كلوب',
    priceUSD: 9.0,
    category: 'Food',
    barcode: '102',
    stock: 25,
    minStockLevel: 8,
    cost: 4.0,
    stockStatus: 'in-stock',
  },
  {
    id: '8',
    name: 'Margherita Pizza',
    nameAr: 'بيتزا مارغريتا',
    priceUSD: 12.0,
    category: 'Food',
    barcode: '103',
    stock: 8,
    minStockLevel: 8,
    cost: 5.0,
    stockStatus: 'low-stock',
  },

  // Bakery
  {
    id: '9',
    name: 'Croissant',
    nameAr: 'كرواسون',
    priceUSD: 3.0,
    category: 'Bakery',
    barcode: '201',
    stock: 50,
    minStockLevel: 12,
    cost: 1.0,
    stockStatus: 'in-stock',
  },
  {
    id: '10',
    name: 'Chocolate Muffin',
    nameAr: 'مافن بالشوكولاتة',
    priceUSD: 3.5,
    category: 'Bakery',
    barcode: '202',
    stock: 40,
    minStockLevel: 12,
    cost: 1.2,
    stockStatus: 'in-stock',
  },
  {
    id: '11',
    name: 'Blueberry Muffin',
    nameAr: 'مافن بالتوت',
    priceUSD: 3.5,
    category: 'Bakery',
    barcode: '203',
    stock: 5,
    minStockLevel: 12,
    cost: 1.2,
    stockStatus: 'low-stock',
  },
  {
    id: '12',
    name: 'Bagel',
    nameAr: 'بيغل',
    priceUSD: 2.5,
    category: 'Bakery',
    barcode: '204',
    stock: 60,
    minStockLevel: 12,
    cost: 0.8,
    stockStatus: 'in-stock',
  },
];
